import type { Category, CampusEvent } from "@/types";
import posterAi from "@/assets/poster-ai-workshop.jpg";
import posterSports from "@/assets/poster-sports-meet.jpg";
import posterCoding from "@/assets/poster-coding-competition.jpg";
import posterCultural from "@/assets/poster-cultural-fest.jpg";
import posterSummit from "@/assets/poster-entrepreneurship-summit.jpg";
import posterCyber from "@/assets/poster-cybersecurity-lecture.jpg";

export const mockCategories: Category[] = [
  {
    id: "cat-technical",
    name: "Technical",
    description: "Hackathons, coding contests and engineering showcases.",
    icon: "Cpu",
    active: true,
    createdAt: "2026-01-12T09:00:00.000Z",
  },
  {
    id: "cat-cultural",
    name: "Cultural",
    description: "Music, dance, drama and campus-wide celebrations.",
    icon: "Music",
    active: true,
    createdAt: "2026-01-14T09:00:00.000Z",
  },
  {
    id: "cat-sports",
    name: "Sports",
    description: "Tournaments, athletics meets and inter-department leagues.",
    icon: "Trophy",
    active: true,
    createdAt: "2026-01-20T09:00:00.000Z",
  },
  {
    id: "cat-workshops",
    name: "Workshops",
    description: "Hands-on sessions led by faculty and industry mentors.",
    icon: "Wrench",
    active: true,
    createdAt: "2026-02-02T09:00:00.000Z",
  },
  {
    id: "cat-seminars",
    name: "Seminars",
    description: "Guest lectures, talks and knowledge sharing sessions.",
    icon: "Presentation",
    active: true,
    createdAt: "2026-02-10T09:00:00.000Z",
  },
  {
    id: "cat-competitions",
    name: "Competitions",
    description: "Quizzes, debates and inter-college challenges.",
    icon: "Medal",
    active: false,
    createdAt: "2026-03-01T09:00:00.000Z",
  },
];

export const mockEvents: CampusEvent[] = [
  {
    id: "evt-ai-workshop-2026",
    name: "AI Workshop 2026",
    categoryId: "cat-workshops",
    organizer: "Department of Computer Science",
    poster: posterAi,
    date: "2026-09-18",
    startTime: "10:00",
    endTime: "16:00",
    venueName: "Innovation Lab, Block C",
    venueDetails: "Second floor, next to the Central Library entrance.",
    registrationRequired: true,
    registrationStart: "2026-08-01",
    registrationEnd: "2026-09-15",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf-ai-workshop/viewform",
    maxParticipants: 120,
    shortDescription:
      "A full-day hands-on workshop on building and deploying practical AI applications.",
    fullDescription:
      "Join us for a full-day, hands-on workshop covering the modern AI stack. Sessions include prompt engineering fundamentals, retrieval augmented generation, fine-tuning small models and shipping an AI feature end to end.\n\nParticipants will work in pairs on a guided project and leave with a deployed demo. Laptops are mandatory; all software used is free.",
    eligibility: "Open to all second, third and final year students.",
    contactPerson: "Dr. Meera Krishnan",
    contactEmail: "meera.krishnan@college.edu",
    contactPhone: "+91 98450 11234",
    instructions: "Bring your own laptop with Python 3.11 installed. Lunch is provided.",
    status: "published",
    createdAt: "2026-07-01T09:00:00.000Z",
  },
  {
    id: "evt-annual-sports-meet",
    name: "Annual Sports Meet",
    categoryId: "cat-sports",
    organizer: "Department of Physical Education",
    poster: posterSports,
    date: "2026-10-02",
    startTime: "07:30",
    endTime: "18:00",
    venueName: "Main Athletics Ground",
    venueDetails: "Assemble at the pavilion gate 30 minutes before your event.",
    registrationRequired: true,
    registrationStart: "2026-09-05",
    registrationEnd: "2026-09-27",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf-sports-meet/viewform",
    maxParticipants: 600,
    shortDescription:
      "Track, field and team events across every department in a single day of competition.",
    fullDescription:
      "The Annual Sports Meet brings together every department for a day of athletics. Events include 100m, 200m, 400m and relay races, long jump, shot put, along with knockout finals for football, basketball and volleyball.\n\nThe closing ceremony and prize distribution begins at 5:00 PM at the pavilion.",
    eligibility: "All enrolled students with a valid college ID.",
    contactPerson: "Coach Rajesh Nair",
    contactEmail: "sports@college.edu",
    contactPhone: "+91 98860 55210",
    instructions: "Sports kit is mandatory. Report to the marshal desk on arrival.",
    status: "published",
    createdAt: "2026-07-08T09:00:00.000Z",
  },
  {
    id: "evt-coding-competition",
    name: "Coding Competition",
    categoryId: "cat-technical",
    organizer: "Coding Club",
    poster: posterCoding,
    date: "2026-08-29",
    startTime: "09:00",
    endTime: "13:00",
    venueName: "Computer Centre, Lab 1-4",
    venueDetails: "Individual workstations are assigned on arrival.",
    registrationRequired: true,
    registrationStart: "2026-08-01",
    registrationEnd: "2026-08-26",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf-coding-contest/viewform",
    maxParticipants: 200,
    shortDescription:
      "A four-hour individual algorithmic contest with prizes for the top ten finishers.",
    fullDescription:
      "A timed algorithmic contest with eight problems of increasing difficulty. Languages supported: C++, Java, Python and JavaScript.\n\nScoring follows ICPC rules. The top ten finishers receive cash prizes and direct entry into the inter-college finals.",
    eligibility: "Open to all students. Individual participation only.",
    contactPerson: "Ananya Rao",
    contactEmail: "codingclub@college.edu",
    contactPhone: "+91 90080 77431",
    instructions: "No external resources or mobile phones allowed inside the lab.",
    status: "published",
    createdAt: "2026-07-11T09:00:00.000Z",
  },
  {
    id: "evt-cultural-fest",
    name: "Cultural Fest",
    categoryId: "cat-cultural",
    organizer: "Students' Cultural Council",
    poster: posterCultural,
    date: "2026-11-13",
    startTime: "16:00",
    endTime: "22:00",
    venueName: "Open Air Amphitheatre",
    venueDetails: "Gates open at 3:30 PM. Seating is unreserved.",
    registrationRequired: false,
    shortDescription:
      "Three stages, twenty performances and the biggest campus celebration of the year.",
    fullDescription:
      "The Cultural Fest is the flagship celebration of the academic year. Expect classical and contemporary dance, a battle of the bands, stand-up comedy and a headline performance to close the night.\n\nFood stalls run by student clubs open from 4:00 PM.",
    eligibility: "Open to all students, staff and invited guests.",
    contactPerson: "Nikhil Verma",
    contactEmail: "cultural@college.edu",
    contactPhone: "+91 99001 24578",
    status: "published",
    createdAt: "2026-07-15T09:00:00.000Z",
  },
  {
    id: "evt-entrepreneurship-summit",
    name: "Entrepreneurship Summit",
    categoryId: "cat-seminars",
    organizer: "Incubation & Innovation Cell",
    poster: posterSummit,
    date: "2026-09-26",
    startTime: "09:30",
    endTime: "17:30",
    venueName: "Senate Hall",
    venueDetails: "Main administrative building, ground floor.",
    registrationRequired: true,
    registrationStart: "2026-09-20",
    registrationEnd: "2026-09-24",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf-summit/viewform",
    maxParticipants: 300,
    shortDescription:
      "Founders, investors and alumni share what it really takes to build a company.",
    fullDescription:
      "A day of keynotes, fireside chats and a live pitch session judged by early-stage investors. Selected student teams get a five-minute slot to pitch for incubation support.\n\nNetworking lunch and a closing mixer are included.",
    eligibility: "Students of all years and departments.",
    contactPerson: "Prof. Sandeep Iyer",
    contactEmail: "incubation@college.edu",
    contactPhone: "+91 98450 90312",
    instructions: "Pitch decks must be submitted 48 hours in advance.",
    status: "published",
    createdAt: "2026-07-19T09:00:00.000Z",
  },
  {
    id: "evt-cybersecurity-lecture",
    name: "Cybersecurity Guest Lecture",
    categoryId: "cat-seminars",
    organizer: "Department of Information Technology",
    poster: posterCyber,
    date: "2026-10-21",
    startTime: "14:00",
    endTime: "16:00",
    venueName: "Seminar Hall B",
    venueDetails: "Academic Block A, first floor.",
    registrationRequired: true,
    registrationStart: "2026-09-25",
    registrationEnd: "2026-10-18",
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf-cyber-lecture/viewform",
    shortDescription:
      "A practitioner's walkthrough of real incident response cases from the last year.",
    fullDescription:
      "Our guest speaker leads a national CERT response team and will walk through anonymised incident case studies: initial access, lateral movement, detection gaps and recovery.\n\nThe session closes with an open Q&A on careers in security.",
    eligibility: "Third and final year IT and CS students.",
    contactPerson: "Dr. Farhan Sheikh",
    contactEmail: "it.dept@college.edu",
    contactPhone: "+91 98800 33119",
    status: "draft",
    createdAt: "2026-07-24T09:00:00.000Z",
  },
];